# Generated by Django 4.0.5 on 2022-06-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhoodApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='hood_logo',
            field=models.ImageField(upload_to=''),
        ),
    ]
