# Generated by Django 4.0.5 on 2022-06-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhoodApp', '0002_alter_neighbourhood_hood_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
